---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role server_utils
# 
# Overview:
#
# Install useful interactive utilities for triange and debugging purposes.
# Typically these would not need to be available on servers as shell access
# is uneccessary.
# 
# Example play:
#
#

- name: Install system packages
  apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present 
    update_cache: yes
  with_items: server_utils_debian_pkgs

- name: Improved screenrc
  copy: >
    dest=/etc/screenrc
    src=etc/screenrc
    owner=root group=root mode=644
