heat_template_version: 2013-05-23

description: >
  HOT template for an edX app server.

parameters:
  image:
    type: string
    description: Image ID or name
    default: ubuntu-12.04-server-cloudimg
  flavor:
    type: string
    description: Flavor to use for app servers
    default: m1.large
  pool_id:
    type: string
    description: Pool to contact
  protocol_port:
    type: number
    description: Protocol port
  user_data:
    type: string
    description: Server user_data
  metadata:
    type: json
  network:
    type: string
    description: Network used by the server
  security_group:
    type: string
    description: Security group used by the server
  key_name:
    type: string
    description: keypair for authentication

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name }
      metadata: { get_param: metadata }
      user_data: { get_param: user_data }
      user_data_format: RAW
      networks: [ { network: { get_param: network } } ]
      security_groups: [ { get_param: security_group } ]
  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: { get_param: pool_id }
      address: { get_attr: [ server, first_address ] }
      protocol_port: { get_param: protocol_port }

outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [ server, first_address ] }
  lb_member:
    description: LB member details.
    value: { get_attr: [ member, show ] }
