---
# Example single-node OpenStack deployment.

- name: Configure instance
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
  roles:
    - role: nginx
      nginx_sites:
      - certs
      - lms
      - cms
      - forum
      - xqueue
      - ecommerce
      nginx_default_sites:
      - lms
    - mysql
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - notifier
    - analytics_api
    - insights
    - edx_notes_api
    - oauth_client_setup
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - ecommerce
    - ecomworker
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - { role: "xqueue", update_users: True }
    - certs
    - demo
